C from Ellis,1982-example 3.2
C THIS PROGRAM CALCULATES THE NETT PAY 
C OF A WORKER WHO PAYS 5% OF HIS GROSS PAY
C TOWARDS HIS SUPERANNUATION, 25% OF WHAT IS LEFT
C AS INCOME TAX, AND ALSO HAS FIXED DEDUCTIONS FOR
C HEALTH INSURANCE AND OTHER WELFARE AMOUNTING 
C AT 14.50$ PER WEEK. THAN SHOWS A PAYSLIP
C SHOWING GROSS PAT, NETT PAY AND ALL DEDUCTIONS
        PROGRAM APPLES
        INTEGER NBOX,NAPPLS,NLEFT
        PRINT *,'please enter the number of boxes'
        PRINT *,'and the number of apples'
        READ *,NBOX,NAPPLS
        N = NAPPLS/NBOX
        NLEFT = NAPPLS-N*NBOX
        PRINT *,N,' FULL CARTOONS'
        PRINT *,NLEFT,' APPLES LEFT OVER'
        END
C ./pay <data/pay.dat
