C from Ellis,1982-example 3.2
C THIS PROGRAM CALCULATES THE NETT PAY 
C OF A WORKER WHO PAYS 5% OF HIS GROSS PAY
C TOWARDS HIS SUPERANNUATION, 25% OF WHAT IS LEFT
C AS INCOME TAX, AND ALSO HAS FIXED DEDUCTIONS FOR
C HEALTH INSURANCE AND OTHER WELFARE AMOUNTING 
C AT 14.50$ PER WEEK. THAN SHOWS A PAYSLIP
C SHOWING GROSS PAT, NETT PAY AND ALL DEDUCTIONS
        PROGRAM PAY
        REAL GROSS,SUPER, XPAY, TAX, PAYNET
        PRINT *,'Please enter gross salary (x week)'
        READ *,GROSS
        SUPER = 0.06*GROSS
        XPAY = GROSS - SUPER
        TAX = 0.25*XPAY
        PAYNET = XPAY - TAX - 14.5
        PRINT *,'GROSS PAY:',GROSS,'$'
        PRINT *,'SUPERANNUATION:',SUPER,'$'
        PRINT *,'TAX:',TAX,'$'
        PRINT *,'INSURANCE:',14.5,'$'
        PRINT *,''
        PRINT *,'NETT PAY:',PAYNET,'$'
        END
C ./pay <data/pay.dat
